# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: lint
      - task: test
      - task: build
  install:
    cmds:
      - go install -ldflags "-X main.commit=$(git rev-parse HEAD) -X main.date=$(date --iso-8601)"
  build:
    cmds:
      - go build -ldflags "-X main.commit=$(git rev-parse HEAD) -X main.date=$(date --iso-8601)"
  test:
    cmds:
      - go test
  fmt:
    cmds:
      - dprint fmt
      - go fmt
  lint:
    # go fmt does not have option for no effect - https://github.com/golang/go/issues/41189
    cmds:
      - dprint check
      - go vet
      - actionlint
  versions:
    cmds:
      - nix --version
      - task --version
      - go version
      - dprint --version
      - actionlint --version
