name: Lint
on:
  push:
    branches: [main]
  pull_request:
jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dprint/check@v2.2
